server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pizzaDB
    username: root
    password: root@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    compatibility-verifier:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect

  application:
    name: user
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: true
    registerWithEureka: true