spring:
  application:
    name: eureka-service
  cloud:
    compatibility-verifier:
      enabled: false
server:
  port: ${EUREKA_SERVER_PORT:8761}

eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false

