server:
  port: 8089
spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/pizzaDb}
  application:
    name: pizza-details
  cloud:
    compatibility-verifier:
      enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
    fetchRegistry: true
    registerWithEureka: true
